# Generated by Django 5.1.1 on 2024-10-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitplan',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=750, max_digits=10),
        ),
    ]
