# Generated by Django 5.1.1 on 2024-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0002_alter_chitplan_interest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid')], default='Pending', max_length=10),
        ),
    ]
