# Generated by Django 5.1.1 on 2024-10-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
