# Generated by Django 5.1.1 on 2024-10-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
