# Generated by Django 5.1.1 on 2024-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0007_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitplan',
            name='plan',
            field=models.IntegerField(choices=[(500, '500'), (1000, '1000')], default=500),
        ),
    ]
