# Generated by Django 5.1.1 on 2024-10-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0008_alter_chitplan_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='installment_number',
        ),
    ]
