# Generated by Django 5.1.1 on 2024-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0009_remove_payment_installment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
