# Generated by Django 5.1.1 on 2024-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0010_payment_installment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='missed_months',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
