# Generated by Django 5.1.1 on 2024-10-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0011_user_missed_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
